# Generated by Django 3.2.19 on 2023-06-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('pk_word_count', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'word_count',
                'managed': True,
            },
        ),
    ]
